# Generated by Django 3.2.4 on 2021-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('summary', models.TextField(max_length=2000)),
                ('experience', models.TextField(max_length=2000)),
                ('phone', models.CharField(max_length=12)),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=300)),
            ],
        ),
    ]
