# Generated by Django 3.1.3 on 2021-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.AddField(
            model_name='profile',
            name='HSC',
            field=models.CharField(default='12', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='SSC',
            field=models.CharField(default='10', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
