# Generated by Django 3.1.3 on 2021-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20210711_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codingprofile',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='https://github.com/', max_length=300),
        ),
    ]
